[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "kubecli-tools"
version = "0.1.0"
description = "CLI unificada para kubectl, kubens, kubectx e oc"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
kubecli = "cli.kubecli:main"

[tool.setuptools.packages.find]
include = ["cli*"]
